Dataframes Part 1

In [1]:
import numpy as np

In [3]:
import pandas as pd

In [7]:
from numpy.random import randn

In [15]:
np.random.randn(4,5) #matrix

array([[ 0.93482709, -0.23986283,  3.05321607,  1.17316841,  1.60865524],
       [ 1.46090987, -0.23216373,  0.44401296,  0.83967207,  0.72877885],
       [ 0.03282882, -0.54907478, -1.44147762,  0.30073012,  0.49906145],
       [-1.0170746 ,  1.06200581,  2.06752738, -0.05650403, -1.67253554]])

In [17]:
np.random.randn(20) #vector

array([-1.51885261,  0.29863068, -1.37201724,  0.78781862,  0.50590953,
       -0.84371725, -0.75236018, -0.15003735,  1.98190348,  0.14419276,
       -0.05880558, -0.73380144, -0.0967593 ,  0.33392664, -1.17121323,
       -1.35122781, -2.26830664,  0.78062151, -0.78900952,  0.40878897])

In [19]:
np.random.seed(101) #just so things stay the same

In [25]:
df = pd.DataFrame(randn(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z']) #data, rownames, column names

In [27]:
df #all verticals are just pandas series 

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [29]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [31]:
type(df['W']) #we pulled out the series 

pandas.core.series.Series

In [35]:
df[['W', 'Z']] #pulled out data frame from df using list

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [70]:
df['New'] = np.random.randn(5)

In [72]:
df

W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119  0.221491
B -0.134841  0.390528  0.166905  0.184502 -0.855196
C  0.807706  0.072960  0.638787  0.329646  1.541990
D -0.497104 -0.754070 -0.943406  0.484752  0.666319
E -0.116773  1.901755  0.238127  1.996652 -0.538235

In [68]:
np.random.randn(5,2)

array([[-2.14121229,  0.99257345],
       [ 1.19224064, -1.04677954],
       [ 1.29276458, -1.46751402],
       [-0.49409536, -0.16253473],
       [ 0.48580874,  0.39248881]])

In [74]:
randn(5)

array([-0.56858136,  1.40733825,  0.64180551, -0.9050999 , -0.39115663])

In [76]:
df['Newer'] = df ['W'] + df ['Y']

In [78]:
df

W         X         Y         Z       New     Newer
A  0.302665  1.693723 -1.706086 -1.159119  0.221491 -1.403420
B -0.134841  0.390528  0.166905  0.184502 -0.855196  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.541990  1.446493
D -0.497104 -0.754070 -0.943406  0.484752  0.666319 -1.440510
E -0.116773  1.901755  0.238127  1.996652 -0.538235  0.121354

In [88]:
df.drop('New') #error because the axis must be specified

KeyError: "['New'] not found in axis"

In [90]:
df.drop('New', axis = 1) #need inplace argument

W         X         Y         Z     Newer
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [92]:
df.drop('E')

W         X         Y         Z       New     Newer
A  0.302665  1.693723 -1.706086 -1.159119  0.221491 -1.403420
B -0.134841  0.390528  0.166905  0.184502 -0.855196  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.541990  1.446493
D -0.497104 -0.754070 -0.943406  0.484752  0.666319 -1.440510

In [ ]:
df.drop('E')

In [94]:
df.drop('New', axis=1, inplace=True)

In [96]:
df

W         X         Y         Z     Newer
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [98]:
df.drop('Newer', axis = 1, inplace=True)

In [100]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [102]:
df.loc['A'] #also a series

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [104]:
df.loc['A']['W']

0.3026654485851825

In [106]:
df.loc['A','W']

0.3026654485851825

In [108]:
df.iloc[0,0] #by index

0.3026654485851825

In [110]:
df.loc[['A', 'B'], ['W', 'X']]

W         X
A  0.302665  1.693723
B -0.134841  0.390528

Dataframes Part 2

In [120]:
bool = df > 0

In [122]:
df[bool]

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [124]:
df[df > 0]

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [127]:
df > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [129]:
df['W'] > 0 #shows the series

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [133]:
df['X'] > 0

A     True
B     True
C     True
D    False
E     True
Name: X, dtype: bool

In [135]:
df[['W','X']] > 0

W      X
A   True   True
B  False   True
C   True   True
D  False  False
E  False   True

In [139]:
df[df[['W','X']] > 0] #you cannot do this

W         X   Y   Z
A  0.302665  1.693723 NaN NaN
B       NaN  0.390528 NaN NaN
C  0.807706  0.072960 NaN NaN
D       NaN       NaN NaN NaN
E       NaN  1.901755 NaN NaN

In [143]:
df[(df['W'] > 0) & (df['X'] > 0)] #you compare them separately instead

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [131]:
df[df['W'] > 0]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [ ]:
#when you use these nested condition values, it only prints out the rows where the condition is True

In [145]:
result = df[df['W'] > 0]

In [147]:
result ['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [173]:
df.loc[:, df.loc['C'] > 0.1]

W         Y         Z
A  0.302665 -1.706086 -1.159119
B -0.134841  0.166905  0.184502
C  0.807706  0.638787  0.329646
D -0.497104 -0.943406  0.484752
E -0.116773  0.238127  1.996652

In [169]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [165]:
df.drop('E')

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [175]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [181]:
df[(df['W'] > 0) and (df['X'] > 0)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
#this does not work as the "and" operator can only compare two values(single bools), while the & can compare multiple bools 

In [183]:
df[(df['W'] > 0) & (df['X'] > 0)]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [ ]:
df[(df['W'] > 0) | (df['X'] > 0)] #same with or, becomes pipe operator

In [185]:
df.reset_index() #resets to number, must use inplace = True to save this to df

index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [ ]:
#the old index becomes a column

In [187]:
df['States'] = ['CA', 'NY', 'NJ', 'PA', 'CT']

In [189]:
df

W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NY
C  0.807706  0.072960  0.638787  0.329646     NJ
D -0.497104 -0.754070 -0.943406  0.484752     PA
E -0.116773  1.901755  0.238127  1.996652     CT

In [270]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      0.302665  1.693723 -1.706086 -1.159119
NY     -0.134841  0.390528  0.166905  0.184502
NJ      0.807706  0.072960  0.638787  0.329646
PA     -0.497104 -0.754070 -0.943406  0.484752
CT     -0.116773  1.901755  0.238127  1.996652

In [ ]:
#to change the index you must make a new column then set the index using set_index(column)

Dataframes Part 1

In [274]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [276]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [234]:
df2 = pd.DataFrame(randn(6,2), hier_index, ['A', 'B'])

In [236]:
df2

A         B
Groups Num                    
G1     1    0.110477 -0.804652
       2    0.253548  0.649148
       3    0.358941 -1.080471
G2     1    0.902398  0.161781
       2    0.833029  0.975720
       3   -0.388239  0.783316

In [238]:
df2.loc['G1']

A         B
Num                    
1    0.110477 -0.804652
2    0.253548  0.649148
3    0.358941 -1.080471

In [240]:
df2.loc['G1'].loc[1, 'A'] #you can build off an original call of G2 using loc

0.11047741113032297

In [242]:
df2.index.names

FrozenList(['Groups', 'Num'])

In [248]:
df2.index.names = ['Groups', 'Num']

In [250]:
df2

A         B
Groups Num                    
G1     1    0.110477 -0.804652
       2    0.253548  0.649148
       3    0.358941 -1.080471
G2     1    0.902398  0.161781
       2    0.833029  0.975720
       3   -0.388239  0.783316

In [254]:
df2.loc['G1'].loc[2, 'B']

0.6491477464471864

In [256]:
df2.loc['G2'].loc[[1,2],'B']

Num
1    0.161781
2    0.975720
Name: B, dtype: float64

In [258]:
df2.loc['G2'].loc[:,'B']

Num
1    0.161781
2    0.975720
3    0.783316
Name: B, dtype: float64

In [266]:
df2.xs(1, level = 'Num')

A         B
Groups                    
G1      0.110477 -0.804652
G2      0.902398  0.161781